# Generated by Django 2.2.6 on 2019-11-19 16:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191114_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('newsletter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
