# Generated by Django 2.2.6 on 2019-11-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191105_0129'),
        ('blog', '0008_member'),
    ]

    operations = [
    ]
