# Generated by Django 2.2.6 on 2019-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191116_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imageq',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='page',
            name='imagew',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
    ]
