# Generated by Django 2.2.6 on 2019-11-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191116_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='imageq',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='imagew',
            new_name='image_two',
        ),
    ]
