# Generated by Django 2.2.6 on 2019-11-16 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
