# Generated by Django 2.2.6 on 2019-11-17 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('video', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
