# Generated by Django 2.2.6 on 2019-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embeded',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
